//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoBaseDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClienteEstudiante
    {
        public int idCliente { get; set; }
        public int idEstudiante { get; set; }
        public string parentesco { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Estudiante Estudiante { get; set; }
    }
}
