//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoBaseDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComprobantePago
    {
        public int idComprobante { get; set; }
        public int nCuenta { get; set; }
        public byte idCobrador { get; set; }
        public decimal valor { get; set; }
        public System.DateTime fechaPago { get; set; }
        public System.DateTime fechaSiguientePago { get; set; }
        public decimal deuda { get; set; }
        public string metodoPago { get; set; }
    
        public virtual Cobrador Cobrador { get; set; }
    }
}
