//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoBaseDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Libro
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Libro()
        {
            this.DetalleContratoes = new HashSet<DetalleContrato>();
            this.ProveedorLibroes = new HashSet<ProveedorLibro>();
        }
    
        public byte idLibro { get; set; }
        public string codigo { get; set; }
        public string titulo { get; set; }
        public string autor { get; set; }
        public decimal pvp { get; set; }
        public short stock { get; set; }
        public string categoria { get; set; }
        public string publico { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleContrato> DetalleContratoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProveedorLibro> ProveedorLibroes { get; set; }
    }
}
