//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoBaseDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProveedorLibro
    {
        public byte idProveedor { get; set; }
        public byte idLibro { get; set; }
        public decimal precioCompra { get; set; }
    
        public virtual Libro Libro { get; set; }
        public virtual Proveedor Proveedor { get; set; }
    }
}
